_aux_: 
  _a: &hidden_channels 4
  _b: &kernel_size 3
  _c: &max_pool_kernel_size 2
  _d: &conv_block1
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.LazyConv3d
        out_channels: 16
        kernel_size: *kernel_size
        stride: 1
      - _target_: torch.nn.MaxPool3d
        kernel_size: *max_pool_kernel_size
      - _target_: torch.nn.LeakyReLU
      - _target_: torch.nn.LazyBatchNorm3d
  _e: &conv_block2
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.LazyConv3d
        out_channels: 64
        kernel_size: *kernel_size
        stride: 1
      - _target_: torch.nn.MaxPool3d
        kernel_size: *max_pool_kernel_size
      - _target_: torch.nn.LeakyReLU
      - _target_: torch.nn.LazyBatchNorm3d
  _f: &conv_block3
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.LazyConv3d
        out_channels: 128
        kernel_size: *kernel_size
        stride: 1
      - _target_: torch.nn.MaxPool3d
        kernel_size: *max_pool_kernel_size
      - _target_: torch.nn.LeakyReLU
      - _target_: torch.nn.LazyBatchNorm3d

_target_: serotiny.models.BasicModel
x_label: image
y_label: class

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0001
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0
  amsgrad: false
  
network:
  _target_: torch.nn.Sequential
  _args_:
    - *conv_block1
    - *conv_block2
    - *conv_block3
    - _target_: serotiny.networks.layers.Flatten
    - _target_: torch.nn.LazyLinear
      out_features: 512
    - _target_: torch.nn.Linear
      in_features: 512
      out_features: 512
    - _target_: torch.nn.Linear
      in_features: 512
      out_features: 256
    - _target_: torch.nn.Linear
      in_features: 256
      out_features: 5
    - _target_: torch.nn.Softmax
loss:
  _target_: torch.nn.CrossEntropyLoss
  
# a function used by `serotiny predict` to store the results of feeding data through the model
save_predictions:
  _target_: cytodata_aics.model_utils.save_predictions_classifier
  _partial_: true

# fields to include in the output for each batch
fields_to_log:
  - id
